# Generated by Django 4.2.2 on 2023-06-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0002_person_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
    ]
