# Generated by Django 4.2.2 on 2023-06-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0003_person_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='messages',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='posts',
            field=models.CharField(default='', max_length=200),
        ),
    ]
