# Generated by Django 4.2.2 on 2023-06-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0004_person_messages_person_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Post',
        ),
    ]
